# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

Vagrant.configure("2") do |config|

  commands = YAML.load_file('commands.yaml')
  commands.each do |command|
    config.vm.provision :shell, inline: command
  end

  servers = YAML.load_file('servers.yaml')
  servers.each do |servers| 

    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"] 
      srv.vm.hostname = servers["name"] 
      srv.vm.network "private_network", ip: servers["ip"], :adapater=>2 
      srv.vm.network :forwarded_port, guest: 22, host: servers["port"] 
    
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"] 
        vb.cpus = servers["cpus"] 
        vb.memory = servers["ram"] 
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "33"]  
      end

      if servers["type"] == "master"
          srv.vm.provision "shell", path: "master.sh"
      else
          srv.vm.provision "shell", path: "worker.sh"
      end  

    end

  end
  
end