apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: dguyhasnoname/game2048:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: game
  name: game-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: game

